version: '3.1'
services:
  vcontrold:
    build: .
    container_name: vcontrold
    restart: always
    devices:
      - /dev/vitocal:/dev/ttyUSB0
    environment:
      MQTTHOST: ${MQTTHOST}
      MQTTPORT: ${MQTTPORT}
      MQTTTOPIC: ${MQTTTOPIC}
      MQTTPASSWORD: ${MQTTPASSWORD}
      MQTTACTIVE: ${MQTTACTIVE}
      MQTTUSER: ${MQTTUSER}
      INTERVAL: ${INTERVAL}
      COMMANDS: ${COMMANDS}
    volumes:
      - ./config:/config
