version: '3.1'
services:
  vcontrold:
    build: .
    container_name: vcontrold
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AL00AKZQ-if00-port0:/dev/vitocal:rwm
    environment:
      MQTTACTIVE: true
      MQTTHOST: 10.0.0.1
      MQTTPORT: 1883
      MQTTTOPIC: vcontrold
      MQTTUSER: ""
      MQTTPASSWORD: ""
      INTERVAL: 30
      COMMANDS: "getTempWWObenIst,getTempWWsoll,getNeigungHK1"
    volumes:
      - ./config:/config
      - ./log:/log

